version: '3.3'
services:
  react-app:
    stdin_open: true # intractive shell
    image: compose-react-app # giving the image name
    container_name: react-app-container # giving the name of the container
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always # what to do when docker container shuts down
    ports:
      - "1234:3000"
    volumes: # mapping the folder with current working directory 
      - /home/node/app/node_modules # don't map node modules to any folder in current working directory
      - .:/home/node/app # map app folder inside the container to the current working directory
  tests:
    stdin_open: true
    tty: true
    container_name: react-test-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm","run","test"] # override the default command